     💖 Sponsored

  < with love & joy /> ❦

github: [FabianaCampanari, Quantum-Software-Development]

open_collective: [fabiana-campanari , quantum-software-development]

custom: ['https://opencollective.com/fabiana-campanari', 'https://opencollective.com/quantum-software-development',
'https://github.com/FabianaCampanari/AI-Chatbots-IBM-Watson']



